export interface Project {
  id: string,
  type?: ["INITIAL_INSPECTION" | "INTERNAL_INSPECTION" | "AUTO_EVALUATION" | "TRAINING"],
  company_id?: string,
  other_logo?: string,
  title: string,
  description: string,
  sector_activity: string,
  country: string,
  city: string,
  state: string,
  status: ['ARCHIVED' | 'DRAFT' | 'ACTIVE' | 'INACTIVE' | 'DEPLOYED'],
  start_date: string,
  end_date: string,
  project_structure?: {},
  archive?: boolean,
  draft?: boolean,
  archived_at?: string,
  draft_at?: string,
  slug?: string,
  deleted_at?: string,
  updated_at?: string,
  created_at?: string,
  creator?: string,
  deployed_at?: string,
}
